apiVersion: apps/v1
kind: Deployment
metadata:
  name: innerpeace-healthcheck
  labels:
    app: innerpeace-healthcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: innerpeace-healthcheck
  template:
    metadata:
      labels:
        app: innerpeace-healthcheck
    spec:
      containers:
      - name: innerpeace-healthcheck
        image: akhilmylaram/innerpeace-healthcheck:20251224-130053-60ed489
        ports:
        - containerPort: 8080
