apiVersion: v1
kind: Service
metadata:
  name: innerpeace-healthcheck-service
  labels:
    app: innerpeace-healthcheck
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30003
  selector:
    app: innerpeace-healthcheck
