apiVersion: v1
kind: Service
metadata:
  name: innerpeace-service
  labels:
    app: innerpeace-app
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30004
  selector:
    app: innerpeace-app
